// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc0GzYYOPOGNxI2Z7k15s-wVMnDdrqooY',
    appId: '1:1086139178315:web:c26af7b154d766ad13dcce',
    messagingSenderId: '1086139178315',
    projectId: 'connect-9b9e2',
    authDomain: 'connect-9b9e2.firebaseapp.com',
    storageBucket: 'connect-9b9e2.firebasestorage.app',
    measurementId: 'G-EL9DWX4T3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB48zA0uBL7Zzf3kfeqWxnEU5ry0IntoJs',
    appId: '1:1086139178315:android:d9e1829ee9760a6213dcce',
    messagingSenderId: '1086139178315',
    projectId: 'connect-9b9e2',
    storageBucket: 'connect-9b9e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXiCQGqP8zS5gADDB5cW5_n2e0r0l_vsM',
    appId: '1:1086139178315:ios:50621db99974c2b713dcce',
    messagingSenderId: '1086139178315',
    projectId: 'connect-9b9e2',
    storageBucket: 'connect-9b9e2.firebasestorage.app',
    iosBundleId: 'com.example.connect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXiCQGqP8zS5gADDB5cW5_n2e0r0l_vsM',
    appId: '1:1086139178315:ios:50621db99974c2b713dcce',
    messagingSenderId: '1086139178315',
    projectId: 'connect-9b9e2',
    storageBucket: 'connect-9b9e2.firebasestorage.app',
    iosBundleId: 'com.example.connect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc0GzYYOPOGNxI2Z7k15s-wVMnDdrqooY',
    appId: '1:1086139178315:web:83b5ba74ecc3382013dcce',
    messagingSenderId: '1086139178315',
    projectId: 'connect-9b9e2',
    authDomain: 'connect-9b9e2.firebaseapp.com',
    storageBucket: 'connect-9b9e2.firebasestorage.app',
    measurementId: 'G-2RYHT3KX8X',
  );
}
